openapi: 3.0.0
info:
  description: |
    This is Googler API. It contains methods to perform various operations with search engines.
    You can find out more about Swagger at
    [http://swagger.io](http://swagger.io) or on
    [irc.freenode.net, #swagger](http://swagger.io/irc/).
  version: "1.0.0"
  title: Googler
tags:
  - name: searchResults
    description: Perform operations on keyword statistics
paths:
  /searchResults:
    get:
      tags:
        - searchResults
      summary: Gets search results from google given a query and a keyword to look for. This operation will provide support for OData queries
      operationId: getSearchResults
      parameters:
        - name: queryString
          in: query
          description: The keywords to pass the search engine
          required: true
          schema:
            type: string
        - name: count
          in: query
          description: Number of results to fetch
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SearchResult'
        '400':
          description: Bad request. Confirm input data and try again.
components:
  schemas:
    SearchResult:
      type: object
      properties:
        domain:
          type: string
                
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://googler.infotrack.com/v1