/* tslint:disable */
/* eslint-disable */
/**
 * Googler
 * This is Googler API. It contains methods to perform various operations with search engines. You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Statistics
 */
export interface Statistics {
    /**
     * 
     * @type {number}
     * @memberof Statistics
     */
    topTenCount?: number;
    /**
     * 
     * @type {number}
     * @memberof Statistics
     */
    topTwentyFiveCount?: number;
    /**
     * 
     * @type {number}
     * @memberof Statistics
     */
    totalMentions?: number;
}
