/* tslint:disable */
/* eslint-disable */
/**
 * Googler
 * This is Googler API. It contains methods to perform various operations with search engines. You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { Statistics } from '../models';
/**
 * StatisticsApi - axios parameter creator
 * @export
 */
export const StatisticsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Gets statistics about google search results given a query and a keyword to look for. This operation will provide support for OData queries
         * @param {string} keywords The keywords to pass the search engine
         * @param {string} website The website
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatistics: async (keywords: string, website: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'keywords' is not null or undefined
            if (keywords === null || keywords === undefined) {
                throw new RequiredError('keywords','Required parameter keywords was null or undefined when calling getStatistics.');
            }
            // verify required parameter 'website' is not null or undefined
            if (website === null || website === undefined) {
                throw new RequiredError('website','Required parameter website was null or undefined when calling getStatistics.');
            }
            const localVarPath = `/statistics`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (keywords !== undefined) {
                localVarQueryParameter['keywords'] = keywords;
            }

            if (website !== undefined) {
                localVarQueryParameter['website'] = website;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * StatisticsApi - functional programming interface
 * @export
 */
export const StatisticsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Gets statistics about google search results given a query and a keyword to look for. This operation will provide support for OData queries
         * @param {string} keywords The keywords to pass the search engine
         * @param {string} website The website
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStatistics(keywords: string, website: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Statistics>>> {
            const localVarAxiosArgs = await StatisticsApiAxiosParamCreator(configuration).getStatistics(keywords, website, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * StatisticsApi - factory interface
 * @export
 */
export const StatisticsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Gets statistics about google search results given a query and a keyword to look for. This operation will provide support for OData queries
         * @param {string} keywords The keywords to pass the search engine
         * @param {string} website The website
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStatistics(keywords: string, website: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Statistics>> {
            return StatisticsApiFp(configuration).getStatistics(keywords, website, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * StatisticsApi - object-oriented interface
 * @export
 * @class StatisticsApi
 * @extends {BaseAPI}
 */
export class StatisticsApi extends BaseAPI {
    /**
     * 
     * @summary Gets statistics about google search results given a query and a keyword to look for. This operation will provide support for OData queries
     * @param {string} keywords The keywords to pass the search engine
     * @param {string} website The website
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StatisticsApi
     */
    public async getStatistics(keywords: string, website: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Statistics>> {
        return StatisticsApiFp(this.configuration).getStatistics(keywords, website, options).then((request) => request(this.axios, this.basePath));
    }
}
